### ISSUE TITLE
NullReferenceException when inheritance and multiple assemblies are used

### ISSUE THREAD

**Issue by Lakritzator** [tom-englert/AutoProperties.Fody#10]
Hello,

I found this nice Fody extension the day before yesterday, and I started using it.
Unfortunately I seem to have hit an error, which prevents me from continuing with my small project.

The problem is only reproducible when using 2 projects.
The final class which needs to be transformed by Autoproperties.Fody is in project 1, this extends another class, which also extends a class, both are in project 2.

An example project, showing the error, is available here:
https://github.com/Lakritzator/AutoPropertiesNullReference

The following the build output when I try to build my **original** project:
```
5>            Fody/AutoProperties:   Executing Weaver
5>            Fody/AutoProperties:   Intercept auto-properties in Dapplo.Config.Tests.ConfigTests.Entities.RegistryTestImpl
5>            Fody/AutoProperties:   	Get => System.Object Dapplo.Config.ConfigurationBase`1::Getter(System.String), Set => System.Void Dapplo.Config.ConfigurationBase`1::Setter(System.Reflection.PropertyInfo,System.Object)
5>            Fody/AutoProperties:   	Intercept ProductName
5>            Fody/AutoProperties:   		Intercept getter
MSBUILD : error : Fody/AutoProperties: Unhandled exception. Weaving aborted.
5>            Fody/AutoProperties:   System.NullReferenceException: Object reference not set to an instance of an object.
5>           at Mono.Cecil.ImportGenericContext.TypeParameter(String type, Int32 position) in C:\projects\cecil\Mono.Cecil\Import.cs:line 96
5>           at Mono.Cecil.DefaultMetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context) in C:\projects\cecil\Mono.Cecil\Import.cs:line 663
5>           at Mono.Cecil.DefaultMetadataImporter.ImportType(TypeReference type, ImportGenericContext context) in C:\projects\cecil\Mono.Cecil\Import.cs:line 506
5>           at Mono.Cecil.DefaultMetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context) in C:\projects\cecil\Mono.Cecil\Import.cs:line 655
5>           at Mono.Cecil.DefaultMetadataImporter.ImportType(TypeReference type, ImportGenericContext context) in C:\projects\cecil\Mono.Cecil\Import.cs:line 506
5>           at Mono.Cecil.DefaultMetadataImporter.ImportMethod(MethodReference method, ImportGenericContext context) in C:\projects\cecil\Mono.Cecil\Import.cs:line 695
5>           at Mono.Cecil.DefaultMetadataImporter.ImportReference(MethodReference method, IGenericParameterProvider context) in C:\projects\cecil\Mono.Cecil\Import.cs:line 759
5>           at Mono.Cecil.ModuleDefinition.ImportReference(MethodReference method, IGenericParameterProvider context) in C:\projects\cecil\Mono.Cecil\ModuleDefinition.cs:line 916
5>           at AutoProperties.Fody.ExtensionMethods.GetReference(MethodReference callee, TypeReference callingType)
5>           at AutoProperties.Fody.PropertyAccessorWeaver.ClassWeaver.PropertyWeaver.<BuildInstructions>d__15.MoveNext()
5>           at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
5>           at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
5>           at AutoProperties.Fody.PropertyAccessorWeaver.ClassWeaver.PropertyWeaver.BuildGetter(FieldDefinition backingField, MethodDefinition getInterceptor)
5>           at AutoProperties.Fody.PropertyAccessorWeaver.ClassWeaver.PropertyWeaver.Execute(MethodDefinition getInterceptor, MethodDefinition setInterceptor)
5>           at AutoProperties.Fody.PropertyAccessorWeaver.ClassWeaver.Execute(Interceptors interceptors)
5>           at AutoProperties.Fody.PropertyAccessorWeaver.Interceptors.Execute()
5>           at AutoProperties.Fody.PropertyAccessorWeaver.Execute()
5>            Fody/AutoProperties:   Finished 'AutoProperties' in 13ms
```

I hope you can tackle this, I haven't worked with Cecil yet so I will probably take a lot of time.

Let me know if you have any questions!

Best wishes,
Robin

**Comment by Lakritzator** [comment]
My current workaround is to duplicate the GetInterceptor/SetInterceptor in the extending class with something like:

```
        [GetInterceptor]
        protected override object Getter(string propertyName)
        {
            return base.Getter(propertyName);
        }
```

A bit less efficiant but at least I can continue on the functional aspect of my project.

I will give a try to fix this, and create a pull-request, but I have some bad experience with fody projects...

**Comment by Lakritzator** [comment]
That looks really good, can't wait to be able to use it!

I still have a question about using AutoProperties.Fody.

I use the new .csproj structure, which uses PackageReference. 

When I add AutoProperties.Fody to a project targeting .NET Framework 4.6.1 (net461), it looks like this
```
    <PackageReference Include="AutoProperties.Fody" Version="1.14.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
```

I cannot use the AutoProperties namespace, changing the following (removing the IncludeAssets) worked:
```
    <PackageReference Include="AutoProperties.Fody" Version="1.14.0">
      <PrivateAssets>all</PrivateAssets>
      <!--IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets-->
    </PackageReference>
```
I'm not even sure if this is the best way, but for now it works... is this a known issue?

**Comment by Lakritzator** [comment]
Just wanted to report back, your fix seems to work great.
Thanks a lot, this probably means a lot for the next version of [Greenshot](https://getgreenshot.org) where I plan to use it to generate configuration classes.

**Comment by tom-englert** [comment]
I the issue with `<IncludeAssets>` still there?
The package reference entries are managed by NuGet, so I would assume it should be able to cope with what it adds.
