### ISSUE TITLE
AmbiguousMatchException when subclass hides an inherited property of different type

### ISSUE THREAD

**Issue by bccv1** [tom-englert/AutoProperties.Fody#7]
No exception if property types are the same (and interception seems to work correctly on both properties).
Occurs with/without the "new" modifier.
v1.10

```csharp
public class BaseClass
{
  public string Prop { get; set; }

  [GetInterceptor]
  protected T GetInterceptor<T>( PropertyInfo propInfo, ref T fieldValue )
  {
    return fieldValue;
  }

  [SetInterceptor]
  protected void SetInterceptor<T>( PropertyInfo propInfo, ref T fieldValue, T newValue )
  {
    fieldValue = newValue;
  }
}


public class SubClass : BaseClass
{
  public int Prop { get; set; }  // no exception if "string"
}


public static void Test()
{
  SubClass test = new SubClass();  // throws
}

/*
System.TypeInitializationException: The type initializer for 'SubClass' threw an exception. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name, BindingFlags bindingAttr)
   at TestConsole.Program.SubClass..cctor()
   --- End of inner exception stack trace ---
   at TestConsole.Program.SubClass..ctor()
   at TestConsole.Program.Test()
*/
```

**Comment by tom-englert** [comment]
I wonder if we should really invest work to support such a design flaw?

**Comment by bccv1** [comment]
Thanks for looking at this! Sorry the example i gave was not the best, i was just giving a minimal repo.

In reality this would be where the subclass property type is derived from the base class property type. Aka return type covariance. eg https://stackoverflow.com/questions/35537666/override-child-class-inherited-property-with-more-derived-type

A better example might be:

```csharp
    public class TxData
    {

    }


    public class FooTxData : TxData
    {

    }


    public abstract class Transaction
    {
      protected abstract TxData GetData();

      public TxData Data => GetData();
    }


    public class FooTransaction : Transaction
    {
      protected override TxData GetData() => this.Data;

      public new FooTxData Data { get; }
    }
```

**Comment by bccv1** [comment]
Wow, response time++ Many thanks again!
