### ISSUE TITLE
Generic classes hang (spin cpu) under certain conditions

### ISSUE THREAD

**Issue by bccv1** [tom-englert/AutoProperties.Fody#8]
Weaved classes with generic properties work fine. Weaved classes that have generic type args often seem to work fine, but will sometimes fail and result in execution hanging while the cpu spins.

Some clues to help try replicate the conditions:
- weaved class (or a base class) has a generic type arg
- generic type is a value-type (ctor will break) or reference-type (prop get/set will break)
- interceptor method(s) must have a 'PropertyInfo' parameter (using either T or object)

Observed failures include spinning (32-bit) or an immediate OutOfMemoryException (64-bit):
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'TestIntercept.ClassWithGenericArg`1' threw an exception.
  Source=TestIntercept
  StackTrace:
   at TestIntercept.ClassWithGenericArg`1..ctor()
   at TestIntercept.Program.Main(String[] args) in C:\TestIntercept\Program.cs:line 56

Inner Exception 1:
OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
```

Tested under dotNet 4.6.2-4.7.2 and C# 7.0-7.3

Affects AutoProperties.Fody 1.2-1.13 (Fody 2.5.0-3.1.3)

Minimal repo:

```csharp
using System.Reflection;
using AutoProperties;

namespace TestIntercept
{
  public class ClassWithGenericArg<TArg>
  {
    public int IntProp { get; set; }
    public string StringProp { get; set; }
    //public TArg GenericProp { get; set; }

    [GetInterceptor]
    protected T GetInterceptor<T>( PropertyInfo propInfo, ref T fieldValue )
      => fieldValue;

    [SetInterceptor]
    protected void SetInterceptor<T>( PropertyInfo propInfo, ref T fieldValue, T newValue )
      => fieldValue = newValue;
  }

  public static class Program
  {
    public static void Main()
    {
      new ClassWithGenericArg<int>();  // breaks

      var obj = new ClassWithGenericArg<string>();  // ok

      string strValue = obj.StringProp;  // breaks
      obj.StringProp = "asd";  // breaks

      int intValue = obj.IntProp;  // breaks
      obj.IntProp = 123;  // breaks
    }
  }
}
```

**Comment by bccv1** [comment]
Tested, confirmed fixed - thanks again for the fast response!
